---
title: Naiyan Jones
timezone: GB
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
email: naiyanjones@gmail.com
description:  Naiyan Jones is  a qualified social researcher from the University of Birmingham specalising in social  research, government and public policy. He has written about the social media website Reddit, British policits and social media policy.'
twitter_username: naiyanjones
github_username: naiyanjones
minimal_mistakes_skin: default
search: true
google_analytics: UA-168799890-2
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
logo: "/assets/images/logo40x40.png"
author:
  name: Naiyan Jones
  avatar: "/assets/images/bio-photo.jpg"
  bio: "*Social researcher with experience in digital and policy. Looking for new
    opportunities.*"
  location: Shrewsbury, UK
  icon: fas fa-map-marker-alt
  links:
  - label: "Email"
    icon: "fas fa-envelope"
    url: "mailto:naiyanjones@gmail.com"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/naiyan-jones-302aa2147/"
  - label: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/NaiyanJones"
  - label: "Medium"
    icon: "fab fa-medium"
    url: "https://medium.com/@naiyanjones"
footer:
  links:
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/naiyan-jones-302aa2147/"
  - label: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/NaiyanJones"
  - label: "Medium"
    icon: "fab fa-medium"
    url: "https://medium.com/@naiyanjones"
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
